### ISSUE TITLE
scaler.pkl

### ISSUE THREAD

**Issue by gauravbajodia** [Alkhaddour/Voice-spoofing-detection#1]
Hi, where are all the pickle files that you have put in the config and directories, do we have to to train/download them from somewhere?

**Comment by Alkhaddour** [comment]
Hi, and sorry for the very late answer, I have no idea why I did not receive any notification about this issue.
Answering your question, all the pickle files are generated from the data processing ([here](https://github.com/Alkhaddour/Voice-spoofing-detection/blob/24069a9da472afc49322b7931ebee8e86707c7dc/data_processing/scaler.py#L62) and [here](https://github.com/Alkhaddour/Voice-spoofing-detection/blob/24069a9da472afc49322b7931ebee8e86707c7dc/data_processing/indexer.py#L45))
